version: '3.4'
services:
  ea_api:
    image: ea_api
    container_name: ea_api
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile
    restart: on-failure
    ports:
      - 5000:80
    depends_on:
      - sqlserver
    networks:
      - ea_network

  ea_webapp:
    image: ea_webapp
    container_name: ea_webapp
    build:
      context: .
      dockerfile: EAWebApp/Dockerfile
    restart: on-failure
    ports:
      - 5001:80
    depends_on:
      - ea_api
    networks:
      - ea_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: 'Password%1#29'
      ACCEPT_EULA: 'Y'
    container_name: sqlserver
    hostname: sqlserver
    restart: always
    ports:
      - '1433:1433'
    networks:
      - ea_network

networks:
  ea_network:
